// Delhi-specific hospitals, donors, ambulances, and locations

export const DELHI_CENTER = { lat: 28.6139, lng: 77.209 }

export const hospitals = [
  {
    id: 1,
    name: "AIIMS Delhi",
    address: "Aurangzeb Road, New Delhi",
    lat: 28.5676,
    lng: 77.2133,
    beds: 24,
    icuBeds: 8,
    oxygen: 45,
    contact: "+91-11-2658-8500",
    emergency: "24/7",
    type: "Government",
    specialists: ["Cardiology", "Neurology", "Trauma"],
    // Phase 2 additions
    ventilators: 15,
    pediatricBeds: 12,
    traumaBeds: 10,
    emergencyWardOpen: true,
    lastVerified: new Date(Date.now() - 5 * 60 * 1000), // 5 minutes ago
    rating: 4.7,
  },
  {
    id: 2,
    name: "Safdarjung Hospital",
    address: "Ring Road, New Delhi",
    lat: 28.5705,
    lng: 77.1823,
    beds: 18,
    icuBeds: 6,
    oxygen: 35,
    contact: "+91-11-2658-5050",
    emergency: "24/7",
    type: "Government",
    specialists: ["General Surgery", "Pediatrics", "Orthopedics"],
    // Phase 2 additions
    ventilators: 10,
    pediatricBeds: 15,
    traumaBeds: 8,
    emergencyWardOpen: true,
    lastVerified: new Date(Date.now() - 15 * 60 * 1000), // 15 minutes ago
    rating: 4.4,
  },
  {
    id: 3,
    name: "Max Healthcare - Saket",
    address: "B-16, Saket, New Delhi",
    lat: 28.525,
    lng: 77.1953,
    beds: 32,
    icuBeds: 12,
    oxygen: 50,
    contact: "+91-11-4650-5000",
    emergency: "24/7",
    type: "Private",
    specialists: ["Cardiology", "Oncology", "Orthopedics"],
    // Phase 2 additions
    ventilators: 20,
    pediatricBeds: 10,
    traumaBeds: 12,
    emergencyWardOpen: true,
    lastVerified: new Date(Date.now() - 3 * 60 * 1000), // 3 minutes ago
    rating: 4.8,
  },
  {
    id: 4,
    name: "Fortis Hospital - Delhi Radisson Blu",
    address: "National Highway 8, Gurgaon",
    lat: 28.4595,
    lng: 77.0603,
    beds: 28,
    icuBeds: 10,
    oxygen: 48,
    contact: "+91-124-4141-414",
    emergency: "24/7",
    type: "Private",
    specialists: ["Cardiac Surgery", "Neurosurgery", "ENT"],
    // Phase 2 additions
    ventilators: 18,
    pediatricBeds: 8,
    traumaBeds: 14,
    emergencyWardOpen: true,
    lastVerified: new Date(Date.now() - 45 * 60 * 1000), // 45 minutes ago
    rating: 4.6,
  },
  {
    id: 5,
    name: "Apollo Hospital - New Delhi",
    address: "Nehru Place, New Delhi",
    lat: 28.5531,
    lng: 77.2503,
    beds: 35,
    icuBeds: 14,
    oxygen: 55,
    contact: "+91-11-2161-8801",
    emergency: "24/7",
    type: "Private",
    specialists: ["General Medicine", "Cardiology", "Gastroenterology"],
    // Phase 2 additions
    ventilators: 22,
    pediatricBeds: 12,
    traumaBeds: 10,
    emergencyWardOpen: true,
    lastVerified: new Date(Date.now() - 10 * 60 * 1000), // 10 minutes ago
    rating: 4.7,
  },
  {
    id: 6,
    name: "Moolchand Hospital",
    address: "Lala Lajpat Rai Road, Delhi",
    lat: 28.5608,
    lng: 77.2353,
    beds: 20,
    icuBeds: 7,
    oxygen: 40,
    contact: "+91-11-4141-4141",
    emergency: "24/7",
    type: "Private",
    specialists: ["Neurology", "Urology", "Trauma"],
    // Phase 2 additions
    ventilators: 12,
    pediatricBeds: 6,
    traumaBeds: 9,
    emergencyWardOpen: true,
    lastVerified: new Date(Date.now() - 120 * 60 * 1000), // 2 hours ago
    rating: 4.5,
  },
]


export const bloodDonors = [
  {
    id: 1,
    name: "Rajesh Kumar",
    blood: "O+",
    area: "Connaught Place",
    lat: 28.6329,
    lng: 77.1901,
    lastDonation: "2025-10-15",
    available: true,
    phone: "98XXXXX001",
    contact: true,
  },
  {
    id: 2,
    name: "Priya Singh",
    blood: "B+",
    area: "South Delhi",
    lat: 28.525,
    lng: 77.1953,
    lastDonation: "2025-09-20",
    available: true,
    phone: "98XXXXX002",
    contact: true,
  },
  {
    id: 3,
    name: "Amit Patel",
    blood: "A-",
    area: "North Delhi",
    lat: 28.7041,
    lng: 77.1025,
    lastDonation: "2025-11-01",
    available: false,
    phone: "98XXXXX003",
    contact: false,
  },
  {
    id: 4,
    name: "Neha Gupta",
    blood: "AB+",
    area: "East Delhi",
    lat: 28.5955,
    lng: 77.3145,
    lastDonation: "2025-10-10",
    available: true,
    phone: "98XXXXX004",
    contact: true,
  },
  {
    id: 5,
    name: "Vikram Sharma",
    blood: "O-",
    area: "West Delhi",
    lat: 28.6505,
    lng: 77.0418,
    lastDonation: "2025-09-15",
    available: true,
    phone: "98XXXXX005",
    contact: true,
  },
  {
    id: 6,
    name: "Deepika Menon",
    blood: "B-",
    area: "Saket",
    lat: 28.525,
    lng: 77.1953,
    lastDonation: "2025-08-30",
    available: true,
    phone: "98XXXXX006",
    contact: true,
  },
]

export const ambulances = [
  {
    id: 1,
    name: "Ambulance 102-001",
    status: "Available",
    area: "Connaught Place",
    lat: 28.6329,
    lng: 77.1901,
    driver: "Suresh Singh",
    contact: "+91-98765-43201",
    type: "Normal",
    vehicleNumber: "DL-1C-1234",
    experience: "8 years",
  },
  {
    id: 2,
    name: "Ambulance 102-002",
    status: "Available",
    area: "South Delhi",
    lat: 28.525,
    lng: 77.1953,
    driver: "Ravi Kumar",
    contact: "+91-98765-43202",
    type: "Cardiac",
    vehicleNumber: "DL-3C-5678",
    experience: "12 years",
  },
  {
    id: 3,
    name: "Ambulance 102-003",
    status: "Busy",
    area: "North Delhi",
    lat: 28.7041,
    lng: 77.1025,
    driver: "Mohan Das",
    contact: "+91-98765-43203",
    type: "Normal",
    vehicleNumber: "DL-5C-9012",
    experience: "5 years",
  },
  {
    id: 4,
    name: "Ambulance 108-004",
    status: "Available",
    area: "East Delhi",
    lat: 28.5955,
    lng: 77.3145,
    driver: "Amit Verma",
    contact: "+91-98765-43204",
    type: "Oxygen",
    vehicleNumber: "DL-7C-3456",
    experience: "10 years",
  },
  {
    id: 5,
    name: "Ambulance 102-005",
    status: "Available",
    area: "West Delhi",
    lat: 28.6505,
    lng: 77.0418,
    driver: "Rajesh Yadav",
    contact: "+91-98765-43205",
    type: "Cardiac",
    vehicleNumber: "DL-2C-7890",
    experience: "15 years",
  },
  {
    id: 6,
    name: "Ambulance 108-006",
    status: "Available",
    area: "Rohini",
    lat: 28.7495,
    lng: 77.0736,
    driver: "Prakash Sharma",
    contact: "+91-98765-43206",
    type: "Oxygen",
    vehicleNumber: "DL-8C-2345",
    experience: "7 years",
  },
]

export const emergencyAlerts = [
  {
    id: 1,
    type: "Blood Requirement",
    title: "Urgent: AB+ Blood Needed",
    hospital: "AIIMS Delhi",
    time: "2 minutes ago",
    priority: "high",
  },
  {
    id: 2,
    type: "Oxygen Shortage",
    title: "Oxygen Cylinders Low at Max Saket",
    hospital: "Max Healthcare - Saket",
    time: "15 minutes ago",
    priority: "medium",
  },
  {
    id: 3,
    type: "Health Notice",
    title: "Seasonal Flu Alert - Practice Precautions",
    hospital: "Delhi Health Department",
    time: "1 hour ago",
    priority: "low",
  },
]

export const areaOptions = [
  "Central Delhi (New Delhi, Connaught Place)",
  "South Delhi (Saket, Nehru Place)",
  "East Delhi (Mayur Vihar, Preet Vihar)",
  "West Delhi (Dwarka, Janakpuri)",
  "North Delhi (North Avenue, Kasturba Nagar)",
  "All Delhi",
]

// ===== PHASE 2 DATA =====

// Crowd Reports
export const crowdReports = [
  {
    id: 1,
    hospitalId: 2,
    reportType: "long_queue" as const,
    description: "30+ minute wait at emergency",
    timestamp: new Date(Date.now() - 25 * 60 * 1000), // 25 minutes ago
    upvotes: 5,
    downvotes: 0,
    verified: false,
    expiresAt: new Date(Date.now() + 95 * 60 * 1000), // expires in 95 minutes
  },
  {
    id: 2,
    hospitalId: 6,
    reportType: "beds_full" as const,
    description: "ICU beds completely occupied",
    timestamp: new Date(Date.now() - 45 * 60 * 1000), // 45 minutes ago
    upvotes: 8,
    downvotes: 1,
    verified: true,
    expiresAt: new Date(Date.now() + 75 * 60 * 1000),
  },
  {
    id: 3,
    hospitalId: 4,
    reportType: "oxygen_shortage" as const,
    description: "Low oxygen supply reported",
    timestamp: new Date(Date.now() - 90 * 60 * 1000), // 90 minutes ago
    upvotes: 3,
    downvotes: 2,
    verified: false,
    expiresAt: new Date(Date.now() + 30 * 60 * 1000),
  },
]

// Emergency Contacts (Sample)
export const sampleEmergencyContacts = [
  {
    id: 1,
    name: "Priya Sharma",
    phone: "+91-98765-11111",
    relationship: "Spouse",
    isPrimary: true,
  },
  {
    id: 2,
    name: "Rajesh Kumar",
    phone: "+91-98765-22222",
    relationship: "Parent",
    isPrimary: false,
  },
]

// Pharmacies with Medicine Inventory
export const pharmacies = [
  {
    id: 1,
    name: "Apollo Pharmacy - Connaught Place",
    address: "Connaught Place, New Delhi",
    lat: 28.6315,
    lng: 77.2167,
    phone: "+91-11-4321-1111",
    is24x7: true,
    type: "private" as const,
    inventory: [
      {
        medicineId: 1,
        medicineName: "Paracetamol 500mg",
        availability: "in_stock" as const,
        price: 25,
        lastUpdated: new Date(),
      },
      {
        medicineId: 2,
        medicineName: "Aspirin 75mg",
        availability: "in_stock" as const,
        price: 45,
        lastUpdated: new Date(),
      },
      {
        medicineId: 3,
        medicineName: "Amoxicillin 500mg",
        availability: "low_stock" as const,
        price: 120,
        lastUpdated: new Date(),
      },
    ],
  },
  {
    id: 2,
    name: "MedPlus - Saket",
    address: "Saket, New Delhi",
    lat: 28.5244,
    lng: 77.2066,
    phone: "+91-11-4321-2222",
    is24x7: false,
    type: "private" as const,
    inventory: [
      {
        medicineId: 1,
        medicineName: "Paracetamol 500mg",
        availability: "in_stock" as const,
        price: 22,
        lastUpdated: new Date(),
      },
      {
        medicineId: 4,
        medicineName: "Insulin (Vial)",
        availability: "in_stock" as const,
        price: 850,
        lastUpdated: new Date(),
      },
      {
        medicineId: 5,
        medicineName: "Salbutamol Inhaler",
        availability: "out_of_stock" as const,
        price: 180,
        lastUpdated: new Date(),
      },
    ],
  },
  {
    id: 3,
    name: "Jan Aushadhi Kendra - Nehru Place",
    address: "Nehru Place, New Delhi",
    lat: 28.5494,
    lng: 77.2501,
    phone: "+91-11-4321-3333",
    is24x7: false,
    type: "government" as const,
    inventory: [
      {
        medicineId: 1,
        medicineName: "Paracetamol 500mg",
        availability: "in_stock" as const,
        price: 10,
        lastUpdated: new Date(),
      },
      {
        medicineId: 2,
        medicineName: "Aspirin 75mg",
        availability: "in_stock" as const,
        price: 15,
        lastUpdated: new Date(),
      },
      {
        medicineId: 6,
        medicineName: "Metformin 500mg",
        availability: "in_stock" as const,
        price: 35,
        lastUpdated: new Date(),
      },
    ],
  },
  {
    id: 4,
    name: "Guardian Pharmacy - Rohini",
    address: "Rohini Sector 7, Delhi",
    lat: 28.7495,
    lng: 77.0736,
    phone: "+91-11-4321-4444",
    is24x7: true,
    type: "private" as const,
    inventory: [
      {
        medicineId: 3,
        medicineName: "Amoxicillin 500mg",
        availability: "in_stock" as const,
        price: 115,
        lastUpdated: new Date(),
      },
      {
        medicineId: 7,
        medicineName: "Omeprazole 20mg",
        availability: "in_stock" as const,
        price: 65,
        lastUpdated: new Date(),
      },
    ],
  },
]

// Doctors with Schedules
export const doctors = [
  {
    id: 1,
    name: "Dr. Amit Sharma",
    specialty: "Cardiology",
    qualifications: ["MBBS", "MD (Cardiology)", "DM"],
    experience: 15,
    hospitalId: 1,
    hospitalName: "AIIMS Delhi",
    rating: 4.8,
    schedule: [
      { day: "monday" as const, startTime: "09:00", endTime: "17:00", isOnDuty: true },
      { day: "tuesday" as const, startTime: "09:00", endTime: "17:00", isOnDuty: true },
      { day: "wednesday" as const, startTime: "09:00", endTime: "17:00", isOnDuty: true },
      { day: "thursday" as const, startTime: "09:00", endTime: "17:00", isOnDuty: true },
      { day: "friday" as const, startTime: "09:00", endTime: "17:00", isOnDuty: true },
    ],
    availableForTeleconsult: true,
    consultationFee: 1500,
  },
  {
    id: 2,
    name: "Dr. Priya Mehta",
    specialty: "Pediatrics",
    qualifications: ["MBBS", "MD (Pediatrics)"],
    experience: 12,
    hospitalId: 2,
    hospitalName: "Safdarjung Hospital",
    rating: 4.6,
    schedule: [
      { day: "monday" as const, startTime: "10:00", endTime: "18:00", isOnDuty: true },
      { day: "wednesday" as const, startTime: "10:00", endTime: "18:00", isOnDuty: true },
      { day: "friday" as const, startTime: "10:00", endTime: "18:00", isOnDuty: true },
    ],
    availableForTeleconsult: true,
    consultationFee: 1200,
  },
  {
    id: 3,
    name: "Dr. Rajesh Kumar",
    specialty: "Neurology",
    qualifications: ["MBBS", "MD (Medicine)", "DM (Neurology)"],
    experience: 18,
    hospitalId: 3,
    hospitalName: "Max Healthcare - Saket",
    rating: 4.9,
    schedule: [
      { day: "tuesday" as const, startTime: "08:00", endTime: "16:00", isOnDuty: true },
      { day: "thursday" as const, startTime: "08:00", endTime: "16:00", isOnDuty: true },
      { day: "saturday" as const, startTime: "08:00", endTime: "14:00", isOnDuty: true },
    ],
    availableForTeleconsult: false,
    consultationFee: 2000,
  },
  {
    id: 4,
    name: "Dr. Sneha Gupta",
    specialty: "Emergency Medicine",
    qualifications: ["MBBS", "MD (Emergency Medicine)"],
    experience: 8,
    hospitalId: 1,
    hospitalName: "AIIMS Delhi",
    rating: 4.7,
    schedule: [
      { day: "monday" as const, startTime: "20:00", endTime: "08:00", isOnDuty: true },
      { day: "tuesday" as const, startTime: "20:00", endTime: "08:00", isOnDuty: true },
      { day: "wednesday" as const, startTime: "20:00", endTime: "08:00", isOnDuty: true },
    ],
    availableForTeleconsult: true,
    consultationFee: 1000,
  },
  {
    id: 5,
    name: "Dr. Vikram Singh",
    specialty: "Orthopedics",
    qualifications: ["MBBS", "MS (Orthopedics)"],
    experience: 20,
    hospitalId: 5,
    hospitalName: "Apollo Hospital - New Delhi",
    rating: 4.8,
    schedule: [
      { day: "monday" as const, startTime: "09:00", endTime: "15:00", isOnDuty: true },
      { day: "wednesday" as const, startTime: "09:00", endTime: "15:00", isOnDuty: true },
      { day: "friday" as const, startTime: "09:00", endTime: "15:00", isOnDuty: true },
    ],
    availableForTeleconsult: false,
    consultationFee: 1800,
  },
]

// Traffic Simulation Data
export const trafficData = {
  peakHours: [
    { start: "08:00", end: "10:00" },
    { start: "17:00", end: "20:00" },
  ],
  trafficMultipliers: {
    low: 1.0,
    moderate: 1.3,
    heavy: 1.8,
    severe: 2.5,
  },
  commonAlerts: [
    {
      id: 1,
      type: "heavy_traffic" as const,
      location: "ITO Junction",
      severity: "high" as const,
      description: "Heavy traffic due to ongoing construction",
    },
    {
      id: 2,
      type: "accident" as const,
      location: "Ring Road near AIIMS",
      severity: "medium" as const,
      description: "Minor accident causing slowdown",
    },
  ],
}

// First Aid Instructions
export const firstAidSteps = [
  {
    id: 1,
    scenario: "Heart Attack",
    steps: [
      "Call emergency services (102/108) immediately",
      "Help the person sit down and rest",
      "Loosen any tight clothing",
      "If person is unconscious and not breathing, start CPR",
      "Give aspirin if available and person is not allergic",
    ],
    warnings: [
      "Do not leave the person alone",
      "Do not give food or water",
      "Do not wait to see if symptoms go away",
    ],
  },
  {
    id: 2,
    scenario: "Choking",
    steps: [
      "Encourage the person to cough",
      "Give 5 back blows between shoulder blades",
      "Give 5 abdominal thrusts (Heimlich maneuver)",
      "Alternate between back blows and abdominal thrusts",
      "Call emergency if object doesn't dislodge",
    ],
    warnings: [
      "Do not perform abdominal thrusts on infants",
      "Do not try to remove object with fingers unless visible",
    ],
  },
  {
    id: 3,
    scenario: "Severe Bleeding",
    steps: [
      "Call emergency services immediately",
      "Apply direct pressure to the wound with clean cloth",
      "Maintain pressure for at least 10 minutes",
      "Elevate the injured area above heart level if possible",
      "Apply additional cloth if blood soaks through (don't remove first cloth)",
    ],
    warnings: [
      "Do not remove embedded objects",
      "Do not apply tourniquet unless trained",
    ],
  },
  {
    id: 4,
    scenario: "Unconsciousness",
    steps: [
      "Check if person is breathing",
      "Call emergency services (102/108)",
      "Place person in recovery position if breathing",
      "Start CPR if not breathing",
      "Monitor breathing until help arrives",
    ],
    warnings: [
      "Do not move person if spinal injury suspected",
      "Do not give anything by mouth",
    ],
  },
]

